@WeatherApi_HostAddress = https://localhost:7202

GET {{WeatherApi_HostAddress}}/weatherforecast/
Accept: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ik41OGNnMTdFRkZsWktMWGxKMTFfeiJ9.eyJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOlsiQWRtaW4iXSwiaXNzIjoiaHR0cHM6Ly9kb21ldHJhaW5hdXRoMC5ldS5hdXRoMC5jb20vIiwic3ViIjoid2luZG93c2xpdmV8YTdhNzM5ZDJhM2Y4NTczOSIsImF1ZCI6WyJodHRwczovL01hZGVVcE5hbWVXZWF0aGVyQXBpIiwiaHR0cHM6Ly9kb21ldHJhaW5hdXRoMC5ldS5hdXRoMC5jb20vdXNlcmluZm8iXSwiaWF0IjoxNzQwNjAyMTQzLCJleHAiOjE3NDA2ODg1NDMsInNjb3BlIjoib3BlbmlkIHByb2ZpbGUiLCJhenAiOiJiUDh0dUI5QjVlbVV2VzhLeHpNQm1kWVVxMzJWZFhuYSJ9.lrwh_Zj0-b7M8O5KOGiQTExPTuUZTVNz81FWhihyUiPLQbRCqrJA2vCzsvAjtUFW-qirzNJSQeiXhnT0Gp96waeqW8F5SM-y0JIsmOyvec6GQVZPtZfP-_jTAz9xbyFpdGtsIvWpVl7osVhR3bW-SZcWo13Cttjc7ZXv_F-N9LpLDZCPBaZLwGmkK6rJq6Dp86XDJmhwkdutqNNBLPq9HTQMgWWP5jQTivq7l2uTMLLvk9CPEzs4YxLADzATx9H1H5AoLAbL-KVZhvF_7QEfTh2hC47Lbas20jqx4zO7vY2wf_LCybyfmB366eRfYSaYXoojjdou8D6R0VKiDQwbuQ
###
